extends:
  - prettier

parser: "@typescript-eslint/parser"

plugins:
  - prettier
  - "@typescript-eslint"

env:
  node: true
  jest: true

rules:
  semi: 0
  key-spacing: 2
  curly: 0
  consistent-return: 0
  space-infix-ops: 2
  camelcase: 0
  no-spaced-func: 2
  no-alert: 2
  eol-last: 2
  comma-spacing: 2
  eqeqeq: 2
  no-var: 2

  # possible errors
  comma-dangle: 0
  no-cond-assign: 2
  no-console: 0
  no-constant-condition: 2
  no-control-regex: 2
  no-debugger: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty-character-class: 2
  no-empty: 2
  no-ex-assign: 2
  no-extra-boolean-cast: 2
  no-extra-parens: 0
  no-extra-semi: 2
  no-func-assign: 2
  no-inner-declarations: 2
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-negated-in-lhs: 2
  no-obj-calls: 2
  no-regex-spaces: 2
  no-sparse-arrays: 2
  no-unexpected-multiline: 2
  no-unreachable: 2
  use-isnan: 2
  valid-typeof: 2
  no-redeclare: 2
  init-declarations: 2
  no-catch-shadow: 2
  no-delete-var: 2
  no-label-var: 2
  no-shadow-restricted-names: 2
  "@typescript-eslint/no-shadow": 2
  no-undef-init: 2
  no-undef: 2
  no-undefined: 2
  "@typescript-eslint/no-unused-vars-experimental": 2
  no-use-before-define: 2
  prettier/prettier: 2
